# Generated by Django 3.2.9 on 2022-02-01 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Soon', 'Soon'), ('Done', 'Done')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
